### ISSUE TITLE
json1.type.compose took a long time

### ISSUE THREAD

**Issue by welkinwong** [ottypes/json1#19]
When I have 100 ot，need 700ms
1000 ot, 5000ms

how to fix it ?

**Comment by josephg** [comment]
Can you give an example of the code you’re running? 

And what version of the library are you using? There might have been a problem with the build causing a debug build to get uploaded to npm.

**Comment by welkinwong** [comment]
I tried the latest version

This is my ot

```
[["rows", ["100", {d: 0}], ["99", {p: 0}]],
["rows", ["98", {p: 0}], ["99", {d: 0}]],
["rows", ["97", {p: 0}], ["98", {d: 0}]],
["rows", ["96", {p: 0}], ["97", {d: 0}]],
["rows", ["95", {p: 0}], ["96", {d: 0}]],
["rows", ["94", {p: 0}], ["95", {d: 0}]],
["rows", ["93", {p: 0}], ["94", {d: 0}]],
["rows", ["92", {p: 0}], ["93", {d: 0}]],
["rows", ["91", {p: 0}], ["92", {d: 0}]],
["rows", ["90", {p: 0}], ["91", {d: 0}]],
["rows", ["89", {p: 0}], ["90", {d: 0}]],
["rows", ["88", {p: 0}], ["89", {d: 0}]],
["rows", ["87", {p: 0}], ["88", {d: 0}]],
["rows", ["86", {p: 0}], ["87", {d: 0}]],
["rows", ["85", {p: 0}], ["86", {d: 0}]],
["rows", ["84", {p: 0}], ["85", {d: 0}]],
["rows", ["83", {p: 0}], ["84", {d: 0}]],
["rows", ["82", {p: 0}], ["83", {d: 0}]],
["rows", ["81", {p: 0}], ["82", {d: 0}]],
["rows", ["80", {p: 0}], ["81", {d: 0}]],
["rows", ["79", {p: 0}], ["80", {d: 0}]],
["rows", ["78", {p: 0}], ["79", {d: 0}]],
["rows", ["77", {p: 0}], ["78", {d: 0}]],
["rows", ["76", {p: 0}], ["77", {d: 0}]],
["rows", ["75", {p: 0}], ["76", {d: 0}]],
["rows", ["74", {p: 0}], ["75", {d: 0}]],
["rows", ["73", {p: 0}], ["74", {d: 0}]],
["rows", ["72", {p: 0}], ["73", {d: 0}]],
["rows", ["71", {p: 0}], ["72", {d: 0}]],
["rows", ["70", {p: 0}], ["71", {d: 0}]],
["rows", ["69", {p: 0}], ["70", {d: 0}]],
["rows", ["68", {p: 0}], ["69", {d: 0}]],
["rows", ["67", {p: 0}], ["68", {d: 0}]],
["rows", ["66", {p: 0}], ["67", {d: 0}]],
["rows", ["65", {p: 0}], ["66", {d: 0}]],
["rows", ["64", {p: 0}], ["65", {d: 0}]],
["rows", ["63", {p: 0}], ["64", {d: 0}]],
["rows", ["62", {p: 0}], ["63", {d: 0}]],
["rows", ["61", {p: 0}], ["62", {d: 0}]],
["rows", ["60", {p: 0}], ["61", {d: 0}]],
["rows", ["59", {p: 0}], ["60", {d: 0}]],
["rows", ["58", {p: 0}], ["59", {d: 0}]],
["rows", ["57", {p: 0}], ["58", {d: 0}]],
["rows", ["56", {p: 0}], ["57", {d: 0}]],
["rows", ["55", {p: 0}], ["56", {d: 0}]],
["rows", ["54", {p: 0}], ["55", {d: 0}]],
["rows", ["53", {p: 0}], ["54", {d: 0}]],
["rows", ["52", {p: 0}], ["53", {d: 0}]],
["rows", ["51", {p: 0}], ["52", {d: 0}]],
["rows", ["50", {p: 0}], ["51", {d: 0}]],
["rows", ["49", {p: 0}], ["50", {d: 0}]],
["rows", ["48", {p: 0}], ["49", {d: 0}]],
["rows", ["47", {p: 0}], ["48", {d: 0}]],
["rows", ["46", {p: 0}], ["47", {d: 0}]],
["rows", ["45", {p: 0}], ["46", {d: 0}]],
["rows", ["44", {p: 0}], ["45", {d: 0}]],
["rows", ["43", {p: 0}], ["44", {d: 0}]],
["rows", ["42", {p: 0}], ["43", {d: 0}]],
["rows", ["41", {p: 0}], ["42", {d: 0}]],
["rows", ["40", {p: 0}], ["41", {d: 0}]],
["rows", ["39", {p: 0}], ["40", {d: 0}]],
["rows", ["38", {p: 0}], ["39", {d: 0}]],
["rows", ["37", {p: 0}], ["38", {d: 0}]],
["rows", ["36", {p: 0}], ["37", {d: 0}]],
["rows", ["35", {p: 0}], ["36", {d: 0}]],
["rows", ["34", {p: 0}], ["35", {d: 0}]],
["rows", ["33", {p: 0}], ["34", {d: 0}]],
["rows", ["32", {p: 0}], ["33", {d: 0}]],
["rows", ["31", {p: 0}], ["32", {d: 0}]],
["rows", ["30", {p: 0}], ["31", {d: 0}]],
["rows", ["29", {p: 0}], ["30", {d: 0}]],
["rows", ["28", {p: 0}], ["29", {d: 0}]],
["rows", ["27", {p: 0}], ["28", {d: 0}]],
["rows", ["26", {p: 0}], ["27", {d: 0}]],
["rows", ["25", {p: 0}], ["26", {d: 0}]],
["rows", ["24", {p: 0}], ["25", {d: 0}]],
["rows", ["23", {p: 0}], ["24", {d: 0}]],
["rows", ["22", {p: 0}], ["23", {d: 0}]],
["rows", ["21", {p: 0}], ["22", {d: 0}]],
["rows", ["20", {p: 0}], ["21", {d: 0}]],
["rows", ["19", {p: 0}], ["20", {d: 0}]],
["rows", ["18", {p: 0}], ["19", {d: 0}]],
["rows", ["17", {p: 0}], ["18", {d: 0}]],
["rows", ["16", {p: 0}], ["17", {d: 0}]],
["rows", ["15", {p: 0}], ["16", {d: 0}]],
["rows", ["14", {p: 0}], ["15", {d: 0}]],
["rows", ["13", {p: 0}], ["14", {d: 0}]],
["rows", ["12", {p: 0}], ["13", {d: 0}]],
["rows", ["11", {p: 0}], ["12", {d: 0}]],
["rows", ["10", {p: 0}], ["11", {d: 0}]],
["rows", ["10", {d: 0}], ["9", {p: 0}]],
["rows", ["8", {p: 0}], ["9", {d: 0}]],
["rows", ["7", {p: 0}], ["8", {d: 0}]],
["rows", ["6", {p: 0}], ["7", {d: 0}]],
["rows", ["5", {p: 0}], ["6", {d: 0}]],
["rows", ["4", {p: 0}], ["5", {d: 0}]],
["rows", ["3", {p: 0}], ["4", {d: 0}]],
["rows", ["2", {p: 0}], ["3", {d: 0}]],
["rows", ["1", {p: 0}], ["2", {d: 0}]]]
```

After passing json1.type.compose

```
["rows",
["1", {p: 11}],
["10", {d: 0, p: 2}],
["100", {d: 1}],
["11", {d: 2, p: 3}],
["12", {d: 3, p: 4}],
["13", {d: 4, p: 5}],
["14", {d: 5, p: 6}],
["15", {d: 6, p: 7}],
["16", {d: 7, p: 8}],
["17", {d: 8, p: 9}],
["18", {d: 9, p: 10}],
["19", {d: 10, p: 12}],
["2", {d: 11, p: 22}],
["20", {d: 12, p: 13}],
["21", {d: 13, p: 14}],
["22", {d: 14, p: 15}],
["23", {d: 15, p: 16}],
["24", {d: 16, p: 17}],
["25", {d: 17, p: 18}],
["26", {d: 18, p: 19}],
["27", {d: 19, p: 20}],
["28", {d: 20, p: 21}],
["29", {d: 21, p: 23}],
["3", {d: 22, p: 33}],
["30", {d: 23, p: 24}],
["31", {d: 24, p: 25}],
["32", {d: 25, p: 26}],
["33", {d: 26, p: 27}],
["34", {d: 27, p: 28}],
["35", {d: 28, p: 29}],
["36", {d: 29, p: 30}],
["37", {d: 30, p: 31}],
["38", {d: 31, p: 32}],
["39", {d: 32, p: 34}],
["4", {d: 33, p: 44}],
["40", {d: 34, p: 35}],
["41", {d: 35, p: 36}],
["42", {d: 36, p: 37}],
["43", {d: 37, p: 38}],
["44", {d: 38, p: 39}],
["45", {d: 39, p: 40}],
["46", {d: 40, p: 41}],
["47", {d: 41, p: 42}],
["48", {d: 42, p: 43}],
["49", {d: 43, p: 45}],
["5", {d: 44, p: 55}],
["50", {d: 45, p: 46}],
["51", {d: 46, p: 47}],
["52", {d: 47, p: 48}],
["53", {d: 48, p: 49}],
["54", {d: 49, p: 50}],
["55", {d: 50, p: 51}],
["56", {d: 51, p: 52}],
["57", {d: 52, p: 53}],
["58", {d: 53, p: 54}],
["59", {d: 54, p: 56}],
["6", {d: 55, p: 66}],
["60", {d: 56, p: 57}],
["61", {d: 57, p: 58}],
["62", {d: 58, p: 59}],
["63", {d: 59, p: 60}],
["64", {d: 60, p: 61}],
["65", {d: 61, p: 62}],
["66", {d: 62, p: 63}],
["67", {d: 63, p: 64}],
["68", {d: 64, p: 65}],
["69", {d: 65, p: 67}],
["7", {d: 66, p: 77}],
["70", {d: 67, p: 68}],
["71", {d: 68, p: 69}],
["72", {d: 69, p: 70}],
["73", {d: 70, p: 71}],
["74", {d: 71, p: 72}],
["75", {d: 72, p: 73}],
["76", {d: 73, p: 74}],
["77", {d: 74, p: 75}],
["78", {d: 75, p: 76}],
["79", {d: 76, p: 78}],
["8", {d: 77, p: 88}],
["80", {d: 78, p: 79}],
["81", {d: 79, p: 80}],
["82", {d: 80, p: 81}],
["83", {d: 81, p: 82}],
["84", {d: 82, p: 83}],
["85", {d: 83, p: 84}],
["86", {d: 84, p: 85}],
["87", {d: 85, p: 86}],
["88", {d: 86, p: 87}],
["89", {d: 87, p: 89}],
["9", {d: 88, p: 0}],
["90", {d: 89, p: 90}],
["91", {d: 90, p: 91}],
["92", {d: 91, p: 92}],
["93", {d: 92, p: 93}],
["94", {d: 93, p: 94}],
["95", {d: 94, p: 95}],
["96", {d: 95, p: 96}],
["97", {d: 96, p: 97}],
["98", {d: 97, p: 98}],
["99", {d: 98, p: 1}],
["len", {r: 100, i: 101}]]
```

**usage time：**
time1:  Sat Jul 11 2020 16:51:17 GMT+0800 (CST) 
time2:  Sat Jul 11 2020 16:51:20 GMT+0800 (CST) 
t2-t1:  3102ms

**Comment by josephg** [comment]
Ok a couple points:

1. I recommend using the current version in npm, not the current master in this repository. By default if you do a `git clone`, you'll be using a debug build of this library (which is about 4x slower because it does lots of extra checks everywhere).
2. It looks like you're trying to use a javascript object as if it were a list, and then you're manually updating every single entry in order to insert something near the start? And you're keeping your own special 'len' key to track the number of items... Use a list (array) instead. With the list operations, the ot-json library will let you insert anywhere you want and all the indexes will be updated automatically. 

If you use an array, your operation can be constructed by writing `json.insertOp([1], 'hi')` (to insert 'hi' at position 1). This should be basically instant.

**Comment by welkinwong** [comment]
> Ok a couple points:
> 
> 1. I recommend using the current version in npm, not the current master in this repository. By default if you do a `git clone`, you'll be using a debug build of this library (which is about 4x slower because it does lots of extra checks everywhere). Instead, `npm install ot-json1` then `const json = require('ot-json1')` in your code.
> 2. It looks like you're trying to use a javascript object as if it were a list, and then you're manually updating every single entry in order to insert something near the start? And you're keeping your own special 'len' key to track the number of items... Use a list (array) instead. With the list operations, the ot-json library will let you insert anywhere you want and all the indexes will be updated automatically.
> 
> If you use an array, your operation can be constructed by writing `json.insertOp([1], 'hi')` (to insert 'hi' at position 1). This should be basically instant. All subsequent items will be shifted automatically, and you can use javascript's builtin `.length` operator to find the length of your list.


Thank you for your suggestions and this great library
i try using npm version, Much faster.

100ot: 20ms
1000ot: 760ms
2000ot: 2800ms

For some reasons, I still need to use objects
Is it possible to be faster?

Thank you again and this library 👍👍👍

**Comment by josephg** [comment]
Sure - don't use compose if you want. You can just construct that operation directly.

Here's an example using the cursor API to make an operation like yours. This will move key '0' -> '1', '1' -> '2', ... '9' -> '10' and increments 'len' using a number-add operation:

```javascript
const json = require('.')

const w = new json.WriteCursor()
for (let i = 0; i < 10; i++) {
  w.writeAtPath([''+i], 'p', i)
  w.writeAtPath([''+(i+1)], 'd', i)
}
w.writeAtPath(['len'], 'na', 1)
console.log(w.get())
```

the result is:

```
[
  [ '0', { p: 0 } ],
  [ '1', { d: 0, p: 1 } ],
  [ '10', { d: 9 } ],
  [ '2', { d: 1, p: 2 } ],
  [ '3', { d: 2, p: 3 } ],
  [ '4', { d: 3, p: 4 } ],
  [ '5', { d: 4, p: 5 } ],
  [ '6', { d: 5, p: 6 } ],
  [ '7', { d: 6, p: 7 } ],
  [ '8', { d: 7, p: 8 } ],
  [ '9', { d: 8, p: 9 } ],
  [ 'len', { na: 1 } ]
]
```

The pickup and drop numbering is slightly different, but that shouldn't matter.

I still think your approach is a bad idea though. If you really need to use an object in your application, I recommend doing edit operations with a list structure, and then you should convert the list into an object just before you actually use it in your app. (Or wherever you need it to be shaped like an object).

**Comment by welkinwong** [comment]
> Sure - don't use compose if you want. You can just construct that operation directly.
> 
> Here's an example using the cursor API to make an operation like yours. This will move key '0' -> '1', '1' -> '2', ... '9' -> '10' and increments 'len' using a number-add operation:
> 
> ```js
> const json = require('.')
> 
> const w = new json.WriteCursor()
> for (let i = 0; i < 10; i++) {
>   w.writeAtPath([''+i], 'p', i)
>   w.writeAtPath([''+(i+1)], 'd', i)
> }
> w.writeAtPath(['len'], 'na', 1)
> console.log(w.get())
> ```
> 
> the result is:
> 
> ```js
> [
>   [ '0', { p: 0 } ],
>   [ '1', { d: 0, p: 1 } ],
>   [ '10', { d: 9 } ],
>   [ '2', { d: 1, p: 2 } ],
>   [ '3', { d: 2, p: 3 } ],
>   [ '4', { d: 3, p: 4 } ],
>   [ '5', { d: 4, p: 5 } ],
>   [ '6', { d: 5, p: 6 } ],
>   [ '7', { d: 6, p: 7 } ],
>   [ '8', { d: 7, p: 8 } ],
>   [ '9', { d: 8, p: 9 } ],
>   [ 'len', { na: 1 } ]
> ]
> ```
> 
> Time for 5000: 270ms. Which is still slow, but not _crazy_. (It'd be faster still constructing the JSON object by hand, and skip using WriteCursor).
> 
> I still think your approach is a bad idea though. If you really need to use an object in your application, I recommend doing edit operations with a list structure, and then you should convert the list into an object just before you actually use it in your app. (Or wherever you need it to be shaped like an object).

Thanks a lot !!!
This helped me a lot

I will change to array in the future
👍👏🙏
