### ISSUE TITLE
Suggestion - use public ledger as content server

### ISSUE THREAD

**Issue by vega113** [ottypes/json1#2]
Hi Joseph.
What do you think about using Ethereum public ledger as the content server? Ethereum is a decentralised p2p public ledger - similar to Bitcoin, but one that allows to include turing complete scripts in transactions and thus allows sophisticated built-in support for smart contracts.
In this way - creating a new document will be similar to creating a new contract. And adding new content would be similar to sending transaction to this contract. Since the transactions are stored in public ledger - everyone can access them and thus read the document content.
I think this suggestion solves some of the issues:
1. Monetisation - whoever wants to create a new document and/or add content pays for it in ether - and this mechanism is supported by Ethereum.
2. User addresses - will be standard ethereum addresses.
Also you don't have to host the content - it is hosted on ethereum blockchain, and paid by users, you just provide a front-end that can read the info from the ledger.
Disclaimer: I am not familiar very deep with Ethereum technology - just read about it and tried the tutorial, so maybe it's harder that I think.

**Comment by josephg** [comment]
This probably isn't the place to talk about it, although I"m not sure where is. I don't know enough about etherium to know whether that'd be feasable and/or work well. I mean, you could almost certainly do it - but do clients need to have the whole history of the blockchain on their machine? Does etherium just have one block chain or would we have one per document? And surely it'd be annoying to have to pay money to make a document...?

**Comment by vega113** [comment]
1. Q: I don't know enough about etherium to know whether that'd be feasable and/or work well.
    A: I suggested ethereum as they provide really sophisticated API for smart contracts, but maybe some altcoin blockchain will suit better.
2. Q: do clients need to have the whole history of the blockchain on their machine?
    A: I think not. At least for bitcoin there are "light wallets" that track only transactions for a specific address, so they are light enough to be used on smartphone.
3. Q: Does etherium just have one block chain or would we have one per document?
    A: A document will be associated with an address, where address is just a hash of public key. Whoever controls the private key - can spend the coins sent to this address. So, I think a document will be an address.  If I understand it correctly - in Ethereum an address can be associated with smart contract.
4. Q: And surely it'd be annoying to have to pay money to make a document.
    A: Someone got to pay... Taking in account that there's no central server that hosts the document, it is logical that whoever wants to create a document (smart contract) pays for it. The payment shouldn't be huge - just a mining fee to be included in the blockchain (or maybe more - depending on what it does, I still not sure how Ethereum calculates fees for smart contracts). But it will allow the smart contract to be hosted on the blockchain in really decentralized manner. There will be no way to shut it down or erase.

Also, it seems to me that since blockchain technology is on the rise now - it might be easier to attract attention if you use this buzzword.

**Comment by josephg** [comment]
This is an interesting idea, but I'm burned on the idea of a blockchain. I'm going to close this issue, though I'd be open to speaking about it in person.
