### ISSUE TITLE
how can i diff 2 json

### ISSUE THREAD

**Issue by aeroyu** [ottypes/json1#24]
i have found https://github.com/kbadk/json0-ot-diff ，it can be support json0，but i can not found the lib support for json1

**Comment by josephg** [comment]
Hi!

I don’t know if anyone has made a diffing library specifically for json1. Maybe you could write one!

Alternately, you could use that library to generate an operation then use the json0 to json1 conversion functions to make a json1 operation.

**Comment by JunsW** [comment]
Check out this lib. [Delta](https://github.com/quilljs/delta)
