### ISSUE TITLE
"invalid JSON key" exception on makeInvertible

### ISSUE THREAD

**Issue by kfina91** [ottypes/json1#28]
**Context:**
I encode colors as strings in json. To ensure, they are always consisted 6 character colors, I decided to use {r: oldColor} + {i: newColor} instead of {es: newColor}. (To my understanding from reading the documentation, two simultaneous {es: newColor} operations could lead to a longer string e.g. FF0000444444, correct?)

**Call:**
`json1.makeInvertible(["color", {r: true}, {i: "FF0000"}], {color: "00FF00"}])`

**Throws:**
`Error: Invalid JSON key`

**Expected result**: 
`["abc", {r: "00FF00"}, {i: "FF0000"}], {color: "00FF00"}]`

**Comment by josephg** [comment]
Yeah your theory is sound but your operation isn’t written correctly. Try:

```
json1.makeInvertible(["abc", {r: true, i: "FF0000"}], {color: "00FF00"}])
```

**Comment by kfina91** [comment]
Thank you for your quick answer! 

> but your operation isn’t written correctly.
I accidently inserted another mistake, because I wanted to simplify the json command for the issue and I messed up the naming. I edited my post above:
`json1.makeInvertible(["abc", {r: true}, {i: "FF0000"}], {color: "00FF00"}])` 
to
`json1.makeInvertible(["color", {r: true}, {i: "FF0000"}], {color: "00FF00"}])`
which has the same behavior. Sorry about that part.

But I see you also combined r and i into a single object. This solved the issue!
Thank you very much!

> It’d be good to make that error message more clear.
I found the line, where the error gets thrown: (cursor.ts line: 303).
`  descend(key: Key) {
    if (!isValidPathItem(key)) throw Error('Invalid JSON key')
    // log('descend', key)
    this.pendingDescent.push(key)
  }`

I suggest changing the function descend like this:
`  descend(key: Key) {
    if (!isValidPathItem(key))
        if (typeof(key) == "object") // if it is an actual key 
            throw Error('Expecting a key (string or number) in the operation, but found "' + JSON.stringify(key) + '".' +
                '(If you have 2 operations at the same location, merge them into one object, e.g. [{r: true}, {i: 1}] into [{r: true, i: 1}])');
        else
            throw Error('Invalid JSON key "' + key + '"');
    // log('descend', key)
    this.pendingDescent.push(key)
  }`
I could create a pull request, if you would prefer it that way (but it's just one function).

**Comment by josephg** [comment]
Thanks - that change isn't quite right (there are other cases here which would cause this problem). Lets leave it for now, but I appreciate the effort!

For what its worth, you can also create operations like this using the helper methods:

```javascript
> require('ot-json1').replaceOp(['color'], 'FF0000', '00FF00')
[ 'color', { r: 'FF0000', i: '00FF00' } ]
```
