### ISSUE TITLE
Computing a Diff

### ISSUE THREAD

**Issue by curran** [ottypes/json1#35]
Greetings,

I'm evaluating feasibility of migrating from JSON0 to JSON1 for [VizHub](https://vizhub.com/), a browser based collaborative code editor. One feature of the JSON0 ecosystem that I have been relying on heavily is computing a diff. I have been using [kbadk/json0-ot-diff](https://github.com/kbadk/json0-ot-diff) for this.

I'm opening this issue to ask, has anyone using JSON1 had any success trying to compute diffs between documents and generating JSON1 ops as output?

To be clear, I'm not proposing to extend this JSON1 codebase to compute diffs, that can live externally to this library. Just probing the space to see if anyone else is doing this. I may try to modify `json0-ot-diff` to work with JSON1, but wanted to first see if anyone else has thought about this.

Related issue [json0-ot-diff: JSON1 OT Diff](https://github.com/kbadk/json0-ot-diff/issues/11).

Thanks!

**Comment by josephg** [comment]
I won't comment on diffing tools, but it should be pretty easy to convert json0 changes to json1. There's a [little library to do this conversion here](https://github.com/ottypes/json0-to-1).

**Comment by curran** [comment]
Thanks! Will have a look at that.

**Comment by curran** [comment]
JSON1 OT Diff landed in `json0-ot-diff`!

https://github.com/kbadk/json0-ot-diff/issues/11

https://github.com/kbadk/json0-ot-diff/pull/19
