### ISSUE TITLE
The problem

### ISSUE THREAD

**Issue by ygs-code** [ottypes/json1#40]
What is the difference between OT-json0 and OT-json1

**Comment by josephg** [comment]
The biggest difference is that JSON1 supports arbitrary object moves, so you can move something from anywhere, to anywhere in a JSON tree. JSON0 only supports moves within lists.

**Comment by ygs-code** [comment]
thank you，I've read the Operational Transformation source code,
This is my study of the operational - the transformation source https://github.com/qq281113270/operational-transformation, but he only supports text ot, I want to learn oT-jSON0 and OT-json0 source codes, but I find them very difficult, much more complex than operational transformation- TXT, but I want to work in OT, I must know this, I hope to learn from you. Can you provide more detailed test cases, or do you have videos to learn about them, or do you have more detailed annotated source code? Thank you.

**Comment by ygs-code** [comment]
ot-json0 的测试用例是coffee，有JavaScript的测试用例么？

**Comment by ygs-code** [comment]
The test case of OT-json0 is coffee, is there any JavaScript test case?

**Comment by josephg** [comment]
No; but if you don’t want to learn coffeescript you can run the coffeescript compiler on the test suite to convert it to javascript. Then read that.

The code is very complex. It’s some of the most complex code I’ve ever written. Im sorry but it is not my job to teach you how it works.
