### ISSUE TITLE
Is it possible to provide a base op for object value copying

### ISSUE THREAD

**Issue by onechunlin** [ottypes/json1#43]
The background is this, in the process of using slate, there is a basic operation called **split_node**，which is：
```
{
   type: 'split_node',
   position: 4,
   path: [0, 0],
   properties: { bold: true },
}
```
and original document like this:
```
[
  {
     type: 'paragraph',
     children: [{ text: 'some text!' }]
  }
]
```
The final expected result after the operation is as follows：
```
[
  {
     type: 'paragraph',
     children: [
         { text: 'some' }
         { text: ' text!' }
     ]
  }
]
```
In order to use ot-json1, I transform the origin path to [0, 'children', 0, 'text']. 

My idea is to use editOp to truncate the previous result and use insertOp to insert the latter result, but I encountered a problem that there is no field in the original op that represents the entire string. 

So my idea is to first copy the previous result to the position of the second result, and then use string truncation to achieve the final effect.

So I want to ask if it is possible to provide a basic **copyOp(formPath, toPath)** to achieve this effect? Or is there any way I haven't thought of, I am very willing to learn！

**Comment by josephg** [comment]
No; sorry. Splitting a node is a remarkably tricky operation to implement in OT / CRDT systems.

I can see why you want it - for rich text. But smarter people than me spent a lot of time trying to make that work at google wave, and they eventually concluded it wasn't the right approach. Collaborative editing for rich text (eg in google docs) usually uses a plain text type, with an "annotations" overlay. The annotations overlay marks the underlying characters as being bold / italics / whatever.

Its in a CRDT context, but the [peritext CRDT](https://www.inkandswitch.com/peritext/) goes into a lot more detail about one way to make this work.

I have no plans to add this feature to ot-json.
